### PR TITLE
Eliminate gratuitous incompatibilities with JATS standard

### PR DESCRIPTION
**Pull request by davidmjones**
[t] = implemented in texml; [h] = implemented in ams-html; [d] = deployed

* [x] Move `<issn>`    outside of `<journal-title-group>`. [t]
* [x] Move `<history>` after `<page-range>`. [t]
* [x] Wrap `\tag` in `<target>`. [t]
* [x] Wrap tables in `table-wrap` instead of `<fig>`. [t]
* [x]  Replace `<ams-meta-group>` by `<kwd-group>` and `<compound-kwd>`? [t]
* [x] Add `kwd-group-type="author"` to author keyword `<kwd-group>`. [t]
* [ ] Use `<private-char>`.
* [ ] Allow `<title-group>` inside `<sec>` and then use it when there is an `<alt-title>`? [Probably not worth it.]

These are more likely to be side-stepped by altering our derived DTD:

* [x] Allow (e.g.) `<def-list>`, `<disp-formula>`, and `<fig>`(?) as direct children of `<statement>` (currently they are required to be wrapped in a `<p>` tag).
* [x] JATS doesn't allow anything except #PCDATA inside `<tex-math>` (e.g., no `<text>`, `<target>`, `<xref>` or `<inline-graphic>`) .
* [x] Allow `@disp-level` on `<app>`.
* [x] Allow `@class` on all elements.
* [x] Add `<ams-meta-group>` (maybe rename) and `<article-citation>` to `<article-meta>`.
* [x] Add `<raw-citation>` to `<ref>`.
* [x] Allow `<alt-title>` inside  `<sec>`.
* [x] Add `@height` and `@width` to `<graphic>` and `<inline-graphic>`.
* [x] Add `@has-qed-box` to `<p>`, `<tex-math>`, and `<statement>`.  (Others?)
* [x] Add `@content-type` to `<def-list>`.
* [x] Add `@ref-label` to `<xref>`.
* [ ] Fit algorithms in somehow.

### CODE REVIEW

**Comment by davidmjones** [comment]
Just to be clear, currently `<journal-meta>` looks like this:

    <journal-meta>
      <journal-id/>
      <journal-title-group>
        <journal-title/>
        <abbrev-journal-title/>
        <issn/>     
      </journal-title-group>
      <publisher>
        ...
      </publisher>
      <self-uri/>
    </journal-meta>

After the change, it will look like this:

    <journal-meta>
      <journal-id/>
      <journal-title-group>
        <journal-title/>
        <abbrev-journal-title/>
      </journal-title-group>
      <issn/>       
      <publisher>
        ...
      </publisher>
      <self-uri/>
    </journal-meta>

Similarly, `<article-meta>` will go from

    <article-meta>
      ...
      <pub-date/>
      <history/>     
      <volume/>
      <issue/>
      <fpage/>
      <lpage/>
      <page-range/
      <permissions/>
      ...
    </article-meta>

to

    <article-meta>
      ...
      <pub-date/>
      <volume/>
      <issue/>
      <fpage/>
      <lpage/>
      <page-range/
      <history/>        
      <permissions/>
      ...
    </article-meta>

**Comment by pkra** [comment]
> JATS doesn't like `<xref>` or `<text>` inside `<tex-math>`.

The latter is unsurprising since `text` isn't a valid JATS tag (last I checked).

**Comment by davidmjones** [comment]
> 

Correct.

**Comment by davidmjones** [comment]
@pkra Was `<target>` the element you were thinking about to use to make `\cssId`  ids visible to the XML parser?  If we adopt that, can we drop the `\cssId` and have you supply it?  I.e., instead of

    <tex-math>\begin{equation}
        e = mc^2 \tag{1}\cssId{X}{}
    \end{equation}</tex-math>

we could do

    <tex-math>\begin{equation}
        e = mc^2 <target id="X">\tag{1}</target>
    \end{equation}</tex-math>

and then you can convert that back to `\tag{1}\cssID{X}{}`?

**Comment by davidmjones** [comment]
Or, as long as we're inventing markup, we could go with

    <tag id="X">1</tag>

but then we'd have to to have something like

    <tag parens="no" id="X">1</tag>

for `\tag*{1}`.

**Comment by pkra** [comment]
Using `target` tags sounds good to me, either outside or inside `\tag`. I don't like a `tag` tag. (Was there a reason we don't use `\label`?)

**Comment by pkra** [comment]
> it might be easier to replace it by a new `<mathjax-math>` (`<tex-mathjax>`?) element.

Sigh, ok. I'd slightly lean to mathjax-tex (if we ever want mathjax-asciimath). Let me know which one you choose.

**Comment by pkra** [comment]
FYI There are a couple of publications with `table-wrap` (used inside `fig`) - but only mcom3432 and some of the old MCLs.

**Comment by pkra** [comment]
> Sigh, ok. I'd slightly lean to mathjax-tex (if we ever want mathjax-asciimath). Let me know which one you choose.

Or something along the lines of `tex-like` to phrase it neutrally. (or ams-math :rofl: )

**Comment by davidmjones** [comment]
> Using `target` tags sounds good to me, either outside or inside `\tag`. I don't like a `tag` tag. (Was there a reason we don't use `\label`?)

Beats me.  What's the difference between `\label` and `\cssId`?

**Comment by davidmjones** [comment]
> FYI There are a couple of publications with `table-wrap` (used inside `fig`) - but only mcom3432 and some of the old MCLs.

Good catch.  Those are still using hand-coded HTML tables from before texml supported tables at all.  texml still wouldn't do a good job of mcom3432's tables (longtable and nested aligns, oh my).

**Comment by pkra** [comment]
> Beats me. What's the difference between `\label` and `\cssId`?

\label behaves like TeX. cssID is more generic ("wrap something inert with this ID around that").

**Comment by davidmjones** [comment]
> > it might be easier to replace it by a new `<mathjax-math>` (`<tex-mathjax>`?) element.
> 
> Sigh, ok. I'd slightly lean to mathjax-tex (if we ever want mathjax-asciimath). Let me know which one you choose.

Never mind.  The actual code I have to duplicate amounts to less than 70 lines; the rest is comments, so for now let's just stick with `<tex-math>` and extend its model.

**Comment by davidmjones** [comment]
Replacing `<ams-meta-group>` by `<kwd-group>` would look something
like this:

    <kwd-group
        vocab="MSC 2020"
        vocab-identifier="https://mathscinet.ams.org/msc/msc2020.html">
    
        <compound-kwd content-type="primary">
          <compound-kwd-part content-type="code">55P43</compound-kwd-part>
          <compound-kwd-part content-type="text">...</compound-kwd-part>
        </compound-kwd>
    
        [...]
    </kwd-group>

where content-type could be either "primary" or "secondary".

**Comment by pkra** [comment]
Will table-wrap get the `position` attribute (like figures)?

**Comment by pkra** [comment]
>  Replace `<ams-meta-group>` by `<kwd-group>` and `<compound-kwd>`?

Will the current `<kwd-group>`'s get some form of differentiating attribute (e.g., `vocab` like MSCs or `kwd-group-type="author"`?

**Comment by davidmjones** [comment]
> Will table-wrap get the `position` attribute (like figures)?

Yes.  Literally the only change I'm proposing it to change the name of the element from "fig" to "table-wrap".

**Comment by davidmjones** [comment]
> > Replace `<ams-meta-group>` by `<kwd-group>` and `<compound-kwd>`?
> 
> Will the current `<kwd-group>`'s get some form of differentiating attribute (e.g., `vocab` like MSCs or `kwd-group-type="author"`)?

Yes, good catch.  I meant to include that.

**Comment by pkra** [comment]
>  Use `<private-char>`

Can I have a sample for this one?

**Comment by pkra** [comment]
> Yes, good catch. I meant to include that.

What do you mean with "include that"?

**Comment by pkra** [comment]
> What do you mean with "include that"?

From F2F, we'll have type="author" now.

**Comment by pkra** [comment]
@davidmjones just to double check: Is this a realistic test?

```
<disp-formula><tex-math><target id="targetMath">\tag{<inline-formula><tex-math>x</tex-math></inline-formula>}</target></tex-math></disp-formula>
```

**Comment by pkra** [comment]
Downstream changes have been rolled out to CI for a first test.

**Comment by davidmjones** [comment]
> 



> From F2F, we'll have type="author" now.

Correction: the attribute is `kwd-group-type` not `type` or `kwd-type` (which is what I originally typed).

**Comment by davidmjones** [comment]
> @davidmjones just to double check: Is this a realistic test?

See tests/tag.tex.

**Comment by pkra** [comment]
> I don't like a `tag` tag. 

I might have to reconsider that.

**Comment by pkra** [comment]
This should be closed, I think.

**Pull request closed without merging**
